version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pnpm install && pnpm build && pnpm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/ai2innovate
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai2innovate
    ports:
      - "5432:5432"
